/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gstiondestock.produit;

import gstiondestock.Db;
import gstiondestock.Home;
import gstiondestock.message;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author bel
 */
public class show_Produit extends javax.swing.JFrame {

    /**
     * Creates new form show_Produit
     */
    public show_Produit() {
        initComponents();
        get_Prouduit("");
    }


    private void get_Prouduit(String searsh) {
          boolean state=(is_archiver.isSelected());
        
          
          String sql="";
        if (searsh=="") {
                sql = "SELECT produits.id_pro AS ID, produits.nom_pro AS NOM_PRODUITS, familles.nom_familles AS FAMILLES "
                    + ",produits.qte_stock AS Quantités,produits.seuil_pro AS SEUIL "
                    + "  FROM produits , familles "
                    + " WHERE produits.id_familles=familles.id_familles  AND produits.archivage_pro="+state+" ORDER BY id_pro DESC";
             
            }else{
                      sql = "SELECT produits.id_pro AS ID, produits.nom_pro AS NOM_PRODUITS, familles.nom_familles AS FAMILLES "
                    + ",produits.qte_stock AS Quantités,produits.seuil_pro AS SEUIL "
                    + "FROM produits , familles "
                    + "WHERE produits.id_familles=familles.id_familles AND produits.archivage_pro="+state+" AND nom_pro LIKE '"+searsh+"%'";  
              }
      
            
        ResultSet rs = Db.SelectAll(sql);
        tab_pro.setModel(DbUtils.resultSetToTableModel(rs));
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_pro = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        searsh = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ar = new javax.swing.JButton();
        is_archiver = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(38, 45, 53));

        tab_pro.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        tab_pro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_pro.setToolTipText("");
        tab_pro.setGridColor(new java.awt.Color(0, 0, 0));
        tab_pro.setShowHorizontalLines(false);
        tab_pro.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tab_pro);

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btn_add.setContentAreaFilled(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        searsh.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        searsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searshActionPerformed(evt);
            }
        });
        searsh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searshKeyTyped(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/archive_1.png"))); // NOI18N
        ar.setContentAreaFilled(false);
        ar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arActionPerformed(evt);
            }
        });

        is_archiver.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        is_archiver.setForeground(new java.awt.Color(255, 255, 255));
        is_archiver.setText("Archivage");
        is_archiver.setContentAreaFilled(false);
        is_archiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                is_archiverActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 157, 215));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produits");

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rechercher");

        jPanel18.setBackground(new java.awt.Color(63, 157, 215));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searsh, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(869, Short.MAX_VALUE)
                        .addComponent(is_archiver)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searsh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(is_archiver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(962, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        // TODO add your handling code here:
        add_Produit  g= new add_Produit(this,true);
        g.setVisible(true);
      
        get_Prouduit("");
       

    }//GEN-LAST:event_btn_addActionPerformed

    private void searshKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searshKeyTyped

String s=searsh.getText();
 get_Prouduit(s);


        // TODO add your handling code here:
    }//GEN-LAST:event_searshKeyTyped

    private void searshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searshActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add_famille your handling code here:
        int row = tab_pro.getSelectedRow();

        if (row != -1) {
            String i = tab_pro.getModel().getValueAt(row, 0).toString();
            String nom = tab_pro.getModel().getValueAt(row, 1).toString();
            String nom_fa = tab_pro.getModel().getValueAt(row, 2).toString();
            String seul = tab_pro.getModel().getValueAt(row, 4).toString();
            
            int id = Integer.parseInt(i);
            float seuil =  Float.parseFloat(seul);
            update_produit g = new update_produit(this, true, id,nom,nom_fa,seuil);
            g.setVisible(true);

        } else {
                  message d=new message(this,true,"Choisissez la ligne que vous souhaitez modifier");
            d.setVisible(true);
            // selct line
        }
        searsh.setText("");
         get_Prouduit("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void arActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arActionPerformed
        // TODO add your handling code here:
        int row = tab_pro.getSelectedRow();
        if (row != -1) {
            String s = tab_pro.getModel().getValueAt(row, 0).toString();
            int id = Integer.parseInt(s);

            boolean state= ! is_archiver.isSelected();
            String sql = "UPDATE  produits SET archivage_pro="+state+" WHERE id_pro="+id;

            if (Db.Update(sql)) {
                if(state){
                    message d = new message(this, true, "Archivage avac succes");
                        d.setVisible(true);

                }else{
               message d = new message(this, true, "Extrait des archives");
                        d.setVisible(true);
                }
                searsh.setText("");
                get_Prouduit("");
            } else {
                if(state)
                {message d = new message(this, true, "Ne pas Archivage");
                    d.setVisible(true);}
                else{
                 message d = new message(this, true, "Ne pas Extrait des archives");
                    d.setVisible(true);
                }
            }

        } else {
          message d = new message(this, true, "Choisissez la ligne que vous souhaitez archivage");
          d.setVisible(true);
            // selct line
        }
    }//GEN-LAST:event_arActionPerformed

    private void is_archiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_is_archiverActionPerformed
        // TODO add your handling code here:
        if(is_archiver.isSelected())
          get_Prouduit("");
        else
        searsh.setText("");
         get_Prouduit("");

    }//GEN-LAST:event_is_archiverActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ar;
    private javax.swing.JButton btn_add;
    private javax.swing.JCheckBox is_archiver;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searsh;
    private javax.swing.JTable tab_pro;
    // End of variables declaration//GEN-END:variables
}
